### ISSUE TITLE
Support changing email

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/bar-lobby#120] opened 2023-02-12 15:33 UTC
![image](https://user-images.githubusercontent.com/1434248/218320571-6e2e3ec6-6f46-4608-8e65-f3dbdbf2ee29.png)

**Comment by dusekj4** [comment] 2023-04-07 04:59
starting to work on it with this issue https://github.com/beyond-all-reason/bar-lobby/issues/159

**Comment by p2004a** [comment] 2024-11-10 21:03
Out of scope for lobby, will need to be handled via website, by design.

**Closed by p2004a** 2024-11-10 21:03 UTC
Labels: enhancement
