### ISSUE TITLE
Support changing password

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/bar-lobby#119] opened 2023-02-12 15:33 UTC
![image](https://user-images.githubusercontent.com/1434248/218320560-6d99e378-929f-45c6-a40d-2047978d63e9.png)

**Comment by dusekj4** [comment] 2023-04-07 04:59
starting to work on it with this issue https://github.com/beyond-all-reason/bar-lobby/issues/159

**Comment by Jazcash** [comment] 2023-04-07 10:16
> starting to work on it with this issue #159

I'm not sure if all the endpoints are there in server/tachyon to support this yet: https://github.com/beyond-all-reason/teiserver/blob/master/documents/tachyon/auth.md

**Comment by p2004a** [comment] 2024-11-10 21:04
Out of scope for lobby, will need to be handled via website, by design.

**Closed by p2004a** 2024-11-10 21:04 UTC
Labels: enhancement
