### ISSUE TITLE
Friends List Transparency

### ISSUE THREAD

**Issue by Descyphal** [beyond-all-reason/bar-lobby#167] opened 2023-03-21 01:06 UTC
Friends list black box carries the same black area as the Direct Messages and Downloads windows and the remainder is transparent. And it does not scroll through my list.

![image](https://user-images.githubusercontent.com/128336457/226496933-23ff1878-5a69-415a-854d-2db53015d8a5.png)

**Comment by thehobojoe** [comment] 2023-03-21 22:25
Does this always happen for you? Mine is correctly length-limited, and I need to scroll to see more: 

https://user-images.githubusercontent.com/3493638/226755634-3ec2a78a-57b7-491a-aaee-439ff8b1f422.mp4

**Comment by Jazcash** [comment] 2023-03-22 19:59
Sorry for the confusion, this was already reported and I fixed here: https://github.com/beyond-all-reason/bar-lobby/issues/141
However, the fix isn't released yet, which is why it's fixed for your local dev setup @thehobojoe

I'm not sure if it's best to mark issues as resolved when they're fixed in master or when a release is made that includes the fix.

**Comment by thehobojoe** [comment] 2023-03-22 21:09
Thanks for the clarification. I definitely think bugs should be closed when the issue is fixed, not when it's released. That could cause minor confusion with anyone dealing with a bug, but as long as we mark the issue resolved pending release it should be fine.

**Comment by Jazcash** [comment] 2023-03-22 21:14
Resolved - pending release!

**Closed by Jazcash** 2023-03-22 21:14 UTC
